package Presentation;
import Application.*;
import Domain.Order;
import javafx.application.Application;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.layout.*;
import javafx.scene.paint.Color;
import javafx.scene.text.Font;
import javafx.stage.Stage;
import java.util.ArrayList;

/**
 * The DriverOrder class is used to show orders generated by the pickup points/partners, that are ready for pickup.
 */
public class DriverOrder extends Application {
    public Stage primaryStage;
    private Group root;
    private AnchorPane menu;
    private int sceneWidth = 1200;
    private int sceneHeight = 900;
    private ArrayList<Order> orderArrayList;
    private int size = 0;

    @Override
    public void start(Stage primaryStage) throws Exception {
        sceneRoot();
        orderDetails();
    }
    /**
     * sceneRoot is the root where the stage and scene is set and shown.
     */
    public void sceneRoot(){
        primaryStage = new Stage();

        root = new Group();
        Scene scene = new Scene(root,sceneWidth,sceneHeight, Color.web("#b8cfcc"));
        primaryStage.setTitle("Dry Cleaning System");
        primaryStage.setScene(scene);
        primaryStage.show();

    }

    /**
     * showDriver is used to load/open the Driver UI from another class.
     */
    public void showDriver() {
        try {
            start(primaryStage);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * orderDetails method is fetching order data from the database and create the UI elements based on
     * the database.
     */
    public void orderDetails(){
        ControllerDriver controller = new ControllerDriver();
        controller.getOrder();
        orderArrayList = controller.orderInfo;
        System.out.println(orderArrayList);


        Label citypPlaceholder;

        for (int i = 0; i < orderArrayList.size(); i++) {

            AnchorPane orderPane = new AnchorPane();
            orderPane.setPrefWidth(1120);
            orderPane.setPrefHeight(70);
            orderPane.setLayoutX(40);
            orderPane.setLayoutY(size += 100);
            orderPane.setStyle("-fx-background-color: red");

            Label namePlaceholder = new Label("Partner name: " + orderArrayList.get(i).getPartnerName());
            namePlaceholder.setLayoutX(25);
            namePlaceholder.setLayoutY(25);
            namePlaceholder.setTextFill(Color.BLACK);
            namePlaceholder.setFont(new Font(16));

            citypPlaceholder = new Label("City: " + orderArrayList.get(i).getCity());
            citypPlaceholder.setLayoutX(320);
            citypPlaceholder.setLayoutY(25);
            citypPlaceholder.setTextFill(Color.BLACK);

            Label addressPlaceholder = new Label("Address: " + orderArrayList.get(i).getAddress());
            addressPlaceholder.setLayoutX(490);
            addressPlaceholder.setLayoutY(25);
            addressPlaceholder.setTextFill(Color.BLACK);

            Label orderNumberPlaceholder = new Label("Order Number: " + orderArrayList.get(i).getOrderNumber());
            orderNumberPlaceholder.setLayoutX(700);
            orderNumberPlaceholder.setLayoutY(25);
            orderNumberPlaceholder.setTextFill(Color.BLACK);

            Label orderDatePlaceholder = new Label("Date: " + orderArrayList.get(i).getOrderDate());
            orderDatePlaceholder.setLayoutX(960);
            orderDatePlaceholder.setLayoutY(25);
            orderDatePlaceholder.setTextFill(Color.BLACK);


            root.getChildren().addAll(orderPane);
            orderPane.getChildren().addAll(namePlaceholder,citypPlaceholder,addressPlaceholder, orderNumberPlaceholder,orderDatePlaceholder);
        }
    }
}
